# -*- coding: utf-8 -*-
"""Python_EstruturasAvancadas_LestCode

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13tUtACQ6-nya90kcZP45RY3Qvmc207zS

# Exercícios Módulo 2 - Estruturas Avançadas
**Let's Code**

1) Faça um programa que olhe todos os itens de uma lista e diga quantos deles são pares.
"""

lista = [1, 2, 3, 13, 66, 89, 92, 100]
contagem = 0

for valor in lista:
    if valor % 2 == 0:
      contagem += 1

print(f'A lista contem {contagem} valores pares.')

"""2) Faça um programa que peça para o usuário digitar uma palavra e imprima cada letra em uma linha."""

palavra = input("Insira uma palavra: ")

for letra in palavra:
  print(letra)

"""3) Faça uma função que receba duas listas e retorna a soma item a item dessas listas.
Exemplo: Se a função receber as listas [1,4,3] e [3,5,1], então a função deve retornar [1+3, 4+5, 3+1] = [4, 9, 4].
"""

def soma(a, b):
    c = []
  
    for i in range(len(a)):
      c.append(a[i]+b[i])
    return c

listagem1 = [6, 7, 2]
listagem2 = [4, 9, 1]

soma(listagem1, listagem2)

"""4) Crie um dicionário cujas chaves são os meses do ano e os valores são a duração (em dias) de cada mês."""

duracao_meses = {
    'Janeiro': '31 dias',
    'Fevereiro': '28 ou 29 dias',
    'Março': '31 dias',
    'Abril': '30 dias',
    'Maio': '31 dias',
    'Junho': '30 dias',
    'Julho': '31 dias',
    'Agosto': '31 dias',
    'Setembro': '30 dias',
    'Outubro': '31 dias',
    'Novembro': '30 dias',
    'Dezembro': '31 dias'
}

"""5) Imprima as chaves seguidas dos seus valores para dicionário criado no exercício anterior."""

for mes in duracao_meses:
  print(f'{mes}: {duracao_meses[mes]}')